basePath: /api
host: localhost:8080
info:
  contact: {}
  description: This project It's a credit simulator which allows users to consult
    loan conditions, based in some payments conditions.
  title: Loan Engine API
  version: "1.0"
paths:
  /loanconditions/v1:
    get:
      consumes:
      - application/json
      description: Get all conditions
      produces:
      - application/json
      responses: {}
      summary: Show the list of loan conditions, fees by age group
      tags:
      - conditions
    post:
      consumes:
      - application/json
      description: update a loan condition by name
      produces:
      - application/json
      responses: {}
      summary: update a loan condition by name
      tags:
      - conditions
  /loansimulations/v1:
    post:
      consumes:
      - application/json
      description: Get a plenty of loan simulations
      produces:
      - application/json
      responses: {}
      summary: Get a plenty of loan simulations
      tags:
      - simulation
swagger: "2.0"
